### ISSUE TITLE
Getting experimental_components_builder is not a known Builder

### ISSUE THREAD

**Issue by nrobi144** [widgetbook/widgetbook#1198]
Followed https://docs.widgetbook.io/next/sam and double-checked `widgetbook/build.yaml` + `widgetbook/pubspec.yaml`, but getting

```
Configuring `widgetbook_generator:experimental_components_builder` in target `widgetbook_workspace:widgetbook_workspace` but this is not a known Builder
```

Full pubspec.yaml:
```
name: widgetbook_workspace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  <private_app_name>:
    path: ../
  widgetbook: ^3.7.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  widgetbook_generator: 3.2.0

flutter:
  uses-material-design: true

```
