### ISSUE TITLE
Question: widgetbook_generator with multiple packages

### ISSUE THREAD

**Issue by mpoimer** [widgetbook/widgetbook#1251]
Hi,

I am trying to generate use cases from multiple local packages inside my flutter project into a widgetbook package and am making good progress, but it seems like the imports in the `*.directories.g.dart` file are not generated correctly.

My folder structure looks as follows:

![image](https://github.com/user-attachments/assets/790ad59b-218a-4219-9e41-b6a9e8360029)

and my build.yaml in the root folder looks like this:

```yaml
targets:
  $default:
    dependencies:
      - main_app
    sources:
      # --
      # Note that it is important to include these in the default target.
      - pubspec.*
      - $package$
      - lib/$lib$
      # --
      - widgetbook/lib/main.dart
      - lib/**
      - main_app
    builders:
      widgetbook_generator:use_case_builder:
        generate_for:
          - lib/**
          - main_app/lib/**
```

This works perfectly fine with the only issue that the imports are not `'package:main_app/widgets/...'` but rather `'../../main_app/lib/widgets/...'`, which does not work.

I have also tried it by prefixing `main_app` with `package:main_app`, but then the directories is missing the widgets from `main_app`.

```yaml
targets:
  $default:
    dependencies:
      - main_app
    sources:
      # --
      # Note that it is important to include these in the default target.
      - pubspec.*
      - $package$
      - lib/$lib$
      # --
      - widgetbook/lib/main.dart
      - lib/**
      - package:main_app/lib/**
    builders:
      widgetbook_generator:use_case_builder:
        generate_for:
          - lib/**
          - package:main_app/lib/**
```   

Am I missing something here or doing something wrong with the `package main_app`?

Any help would be greatly appreciated!

Thanks
