### ISSUE TITLE
Long knob list isn't scrollable 

### ISSUE THREAD

**Issue by TahaTesser** [widgetbook/widgetbook#1310]
Create a long knob list that overflows the window and try to reach the bottom of the list.

### Code sample

```dart
@widgetbook.UseCase(name: 'AnimatedSizeExample', type: AnimatedSizeExample)
Widget myWidget(BuildContext context) {
  return Center(
    child: AnimatedSizeExample(
      duration: context.knobs.duration(
        label: 'Animation Duration',
        initialValue: const Duration(milliseconds: 500),
      ),
      curve: context.knobs.list(
        label: 'Animation Curve',
        options: [
          Curves.bounceOut,
          Curves.bounceIn,
          Curves.bounceInOut,
          Curves.easeIn,
          Curves.easeOut,
          Curves.easeInOut,
          Curves.linear,
          Curves.decelerate,
          Curves.elasticIn,
          Curves.elasticOut,
          Curves.elasticInOut,
          Curves.fastOutSlowIn,
          Curves.slowMiddle,
          Curves.ease,
        ],
      ),
    ),
  );
}
```

### Demo

https://github.com/user-attachments/assets/28e1b651-b2b9-4cb9-bd24-234bff8e34aa

```yml
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  widgetbook_annotation: ^3.2.0
  widgetbook: ^3.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  build_runner:
  widgetbook_generator: ^3.9.0

```
