### ISSUE TITLE
bug: widgetbook breaks with dart 3.6.0 workspace

### ISSUE THREAD

**Issue by lume-code** [widgetbook/widgetbook#1326]
**Description**
Apparently widgetbook looks for pubspec.lock file when generating the use cases which might not be present when we are in a dart workspace. dart workspace moved the pubspec.lock to the root workspace directory.

**Steps To Reproduce**

Create a workspace in dart 3.6 (Flutter 3.27.0) and add a widgetbook project. Then run build_runner's build command. It will throw PathNotFoundException: Cannot open file, path = 'pubspec.lock' error.

**Expected Behavior**
Generate use cases. Either gracefully skip subspec.lock file not being found or look for it in the workspace root if not found in current directory.

**Comment by yousinix** [comment]
Hello @manlyman29 👋 
Thanks for reporting this issue!

We have merged a fix, but it might take a couple of days until it's released, as we might need more time resolving any potential issues with the latest Flutter release.
For now, you can use the fix directly from `main` branch as follows:

```
dev_dependencies:
  widgetbook_generator:
    git:
      url: git://github.com/widgetbook/widgetbook.git
      path: packages/widgetbook_generator/
      ref: main
```
