### ISSUE TITLE
widgetbook 3.14.1 doesn't compile when using `NoneDevice`

### ISSUE THREAD

**Issue by Peetee06** [widgetbook/widgetbook#1474]
Widgetbook 3.14.1 doesn't compile when using `NoneDevice`.

It seems like `device_frame_plus` [v1.4.0 removed freezed](https://pub.dev/packages/device_frame_plus/changelog#140) and the `NoneDevice` relies on a type generated by freezed.

![Image](https://github.com/user-attachments/assets/09ad8640-bcb9-4a55-ad4f-cd0e90a95a42)

**Comment by Peetee06** [comment]
Temporary workaround:

Add this to your `pubspec.yaml`:
```yaml
dependencies:
# your dependencies

dev_dependencies:
# your dev dependencies

dependency_overrides:
  device_frame_plus: <1.4.0
```
