### ISSUE TITLE
docs: code for review setup is not properly displayed

### ISSUE THREAD

**Issue by jenshor** [widgetbook/widgetbook#264]
Is showing:

```bash
name: Build 
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Setup flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Run build runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build Website
        run: flutter build web -t lib/main.widgetbook.dart

      - name: Install Widgetbook CLI
        run: dart pub global activate widgetbook_cli

      - name: Upload Widgetbook
        run: |
          widgetbook-cli \
                --path "./" --api-key <API-KEY> \
                --branch \
                $GITHUB_HEAD_REF \
                --repository \
                $GITHUB_REPOSITORY \
                --commit \
                $GITHUB_SHA \
                --actor \
                $GITHUB_ACTOR \
                --base-branch \
                $GITHUB_BASE_REF \
                --base-commit \
                $ \
                --git-provider \
                "GitHub"
```

But should be: 

```yaml
name: Build 
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Setup flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Run build runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build Website
        run: flutter build web -t lib/main.widgetbook.dart

      - name: Install Widgetbook CLI
        run: dart pub global activate widgetbook_cli

      - name: Upload Widgetbook
        run: |
          widgetbook \
                --path "./" --api-key <API-KEY> \
                --branch \
                $GITHUB_HEAD_REF \
                --repository \
                $GITHUB_REPOSITORY \
                --commit \
                $GITHUB_SHA \
                --actor \
                $GITHUB_ACTOR \
                --base-branch \
                $GITHUB_BASE_REF \
                --base-commit \
                ${{ github.event.pull_request.base.sha }} \
                --git-provider \
                "GitHub"
```

**Comment by jenshor** [comment]
For everybody coming from [docs.widgetbook.io](docs.widgetbook.io), please copy the code below:

```yaml
name: Build 
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Setup flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Run build runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build Website
        run: flutter build web -t lib/main.widgetbook.dart

      - name: Install Widgetbook CLI
        run: dart pub global activate widgetbook_cli

      - name: Upload Widgetbook
        run: |
          widgetbook \
                --path "./" --api-key <API-KEY> \
                --branch \
                $GITHUB_HEAD_REF \
                --repository \
                $GITHUB_REPOSITORY \
                --commit \
                $GITHUB_SHA \
                --actor \
                $GITHUB_ACTOR \
                --base-branch \
                $GITHUB_BASE_REF \
                --base-commit \
                ${{ github.event.pull_request.base.sha }} \
                --git-provider \
                "GitHub"
```
