### ISSUE TITLE
Incompatible with widgetbook - can't add to a project

### ISSUE THREAD

**Issue by magillus** [widgetbook/widgetbook#54]
I tried to add to test widgetbook with my last project and run into issue with adding dependency.

**error**:
```

Running "flutter pub get" in magillus_com...                    
Because every version of flutter_test from sdk depends on meta 1.3.0 and widgetbook >=0.0.10 depends on meta ^1.7.0, flutter_test from sdk is incompatible with widgetbook >=0.0.10.

So, because magillus_com depends on both widgetbook ^0.0.16 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because magillus_com depends on both widgetbook ^0.0.16 and flutter_test any from sdk, version solving failed.)
```

**pubspec.yaml**:
```
name: magillus_com
description: A website

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  widgetbook: ^0.0.16
  flutter_fimber: "^0.6.1"
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
...
```

**flutter doctor **:
```
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on Ubuntu 20.04.3 LTS 5.11.0-38-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
[✓] VS Code (version 1.61.2)
[✓] Connected device (2 available)

• No issues found!
```

Same issue on all channels of Flutter.
