### ISSUE TITLE
3.0.0-rc.1: KnobsBuilder.list labelBuilder has wrong signature

### ISSUE THREAD

**Issue by BazinC** [widgetbook/widgetbook#726]
When you use context.knobs.list<T>, the labelBuilder parameter is a `String Function(dynamic)?`.
I think it should be `String Function(T)?`.

**Comment by BazinC** [comment]
whoops, I just saw it was fixed yesterday but not released yet 😁 Sorry
https://github.com/widgetbook/widgetbook/commit/9d455e92f6eb93894ec6cbb10a255086761e9f2c
Thank you @YoussefRaafatNasry

**Comment by YoussefRaafatNasry** [comment]
@BazinC We have been practicing mind-reading here at Widgetbook.
We will release another `rc` version soon with a lot of bug fixes, to get one step closer to the stable version. Feel free to use the `main` branch as follows:

```yaml
dependencies:
  widgetbook:
    git:
      url: https://github.com/widgetbook/widgetbook.git
      path: packages/widgetbook

dependencies_overrides:
  widgetbook_core:
    git:
      url: https://github.com/widgetbook/widgetbook.git
      path: packages/widgetbook_core
```
