### ISSUE TITLE
Conflicting outputs with 3.0.0-RC1

### ISSUE THREAD

**Issue by westito** [widgetbook/widgetbook#734]
**Description**

I get this error when I try to generate after update to `RC1`. Was working on `beta.11`:

`
Both widgetbook_generator:app_builder and source_gen:combining_builder may output lib/ui/home/menu_page.g.dart.  Potential outputs must be unique across all builders. See  https://github.com/dart-lang/build/blob/master/docs/faq.md#why-do-builders-need-unique-outputs
`

**Steps To Reproduce**

Add `json_serializable` to dev_dependencies

```yaml
dev_dependencies:
  json_serializable: ^6.7.0
  widgetbook_generator: ^3.0.0-rc.1
```

**Comment by YoussefRaafatNasry** [comment]
This will be fixed in `rc.2`, which will be released very soon.
As a workaround for now, please use the following snippet in `build.yaml`:

```yaml
targets:
  $default:
    builders:
      // Your other builders...
      widgetbook_generator:app_builder:
        generate_for:
          - 'lib/app.widgetbook.dart' # Match this path with your widgetbook app file
      source_gen:combining_builder:
        generate_for:
          exclude:
            - 'lib/app.widgetbook.dart' # Match this path with your widgetbook app file
```
