### ISSUE TITLE
Path mapping for mono repo setups

### ISSUE THREAD

**Issue by kaptnkoala** [widgetbook/widgetbook#791]
**Description**
When using the Review feature with a mono repository setup, where the names for the widget packages does not correspond to the directory name of the package, no changes in use case or component files are detected, so that no review information is uploaded to Widgetbook Cloud. 

**Steps To Reproduce**

1. Create a simple mono repo setup
2. Create a package project_shared that goes into the directory shared
3. Create a package project_catalog and add the shared package as a local path dependency
4. Create a simple widget with use case in the shared package.
5. Build the Widgetbook catalog app
6. Publish the catalog app with the `--base-branch' flag

**Expected Behavior**
Dependencies from local paths should be supported without any further configuration.

**Additional Context**
We are currently using a fork of the Widgetbook repository, where we added a temporary workaround to define the mapping between the package name and the package directory via build options for the build_runner. The code for the workaround can be fouond [here](https://github.com/widgetbook/widgetbook/compare/main...lotum:widgetbook:feature/path-mapping). When it is not possible to access the mapping between package name and directory in the UseCaseBuilder, this is probably the way to go.

Our corresponding build.yaml file looks like this:

```yaml
global_options:
  widgetbook_generator:use_case_builder:
    options:
      path_mapping:
        project_catalog: catalog
        project_shared: shared
```

**Comment by YoussefRaafatNasry** [comment]
Hello @kaptnkoala 👋 

Apology this took so much time, but the good news is that we came up with a solution that works out of the box and doesn't need a builder configuration.

We need your help validating that this solution works for your setup as well.
You can validate the files generated inside `.dart_tool/build/generated/{package_name}/**/*.usecase.widgetbook.json` have the correct `componentDefinitionPath` (same as the one provided by your solution above).

You can add the generator from GitHub as follows to test it out:

```yaml
dev_dependencies:
  widgetbook_generator:
    git:
      url: git://github.com/widgetbook/widgetbook.git
      path: packages/widgetbook_generator/
      ref: fix/generator/resolve-local-pkgs
```
